name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.1.2, 3.0.4, 2.7.6]

    env:
      FPM_FRY_DOCKER: yes

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install gems
        run: bundle install
      - name: Prepare test environment
        run: bundle exec rake test:setup
      - name: Run tests
        run: bundle exec rake test:all
